# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0004_disk_disk_size_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='disk_size_used',
            new_name='disk_usedsize',
        ),
    ]
