# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0006_disk_disk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='disk_id',
        ),
    ]
