# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0007_remove_disk_disk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_percent',
            field=models.FloatField(default=0),
        ),
    ]
