# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0010_disk_disk_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_mountpoint',
            field=models.CharField(default='', max_length=100),
        ),
    ]
