# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0011_disk_disk_mountpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_shown',
            field=models.IntegerField(default=1),
        ),
    ]
