# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0013_auto_20170413_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_id',
            field=models.IntegerField(default=0),
        ),
    ]
